// Runs before `vite dev` and `vite build` (predev/prebuild hooks).
// Writes public/sitemap-i18n.xml: one <url> per route per supported locale,
// each with xhtml:link alternates for every language + x-default (French).

import { writeFileSync } from "fs";
import { resolve } from "path";

const BASE_URL = "https://ree3franc.com";
const DEFAULT_LOCALE = "fr";
const LOCALES = ["fr", "en", "es", "de", "it", "pt", "ja", "zh"] as const;

// Keep in sync with APP_ROUTES in src/App.tsx (public, indexable routes only).
const ROUTES: Array<{ path: string; changefreq: string; priority: string }> = [
  { path: "/", changefreq: "daily", priority: "1.0" },
  { path: "/prime-video", changefreq: "daily", priority: "0.9" },
  { path: "/decouvrir", changefreq: "weekly", priority: "0.9" },
  { path: "/shop", changefreq: "weekly", priority: "0.9" },
  { path: "/anime-catalog", changefreq: "weekly", priority: "0.8" },
  { path: "/anime-countdown", changefreq: "weekly", priority: "0.7" },
  { path: "/actualites", changefreq: "daily", priority: "0.8" },
  { path: "/leaderboard", changefreq: "weekly", priority: "0.5" },
  { path: "/contact", changefreq: "monthly", priority: "0.5" },
  { path: "/legals", changefreq: "yearly", priority: "0.3" },
];

function localizedUrl(locale: string, path: string) {
  if (locale === DEFAULT_LOCALE) return `${BASE_URL}${path}`;
  return path === "/" ? `${BASE_URL}/${locale}` : `${BASE_URL}/${locale}${path}`;
}

function buildEntry(locale: string, route: (typeof ROUTES)[number]) {
  const alternates = [
    ...LOCALES.map(
      (l) => `    <xhtml:link rel="alternate" hreflang="${l}" href="${localizedUrl(l, route.path)}" />`,
    ),
    `    <xhtml:link rel="alternate" hreflang="x-default" href="${localizedUrl(DEFAULT_LOCALE, route.path)}" />`,
  ].join("\n");

  return [
    `  <url>`,
    `    <loc>${localizedUrl(locale, route.path)}</loc>`,
    `    <changefreq>${route.changefreq}</changefreq>`,
    `    <priority>${route.priority}</priority>`,
    alternates,
    `  </url>`,
  ].join("\n");
}

const body = LOCALES.flatMap((locale) => ROUTES.map((route) => buildEntry(locale, route))).join("\n\n");

const xml = [
  `<?xml version="1.0" encoding="UTF-8"?>`,
  `<!-- Generated by scripts/generate-sitemap-i18n.ts - do not edit by hand. -->`,
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"`,
  `        xmlns:xhtml="http://www.w3.org/1999/xhtml">`,
  body,
  `</urlset>`,
  ``,
].join("\n");

writeFileSync(resolve("public/sitemap-i18n.xml"), xml);
console.log(`sitemap-i18n.xml written (${LOCALES.length * ROUTES.length} URLs)`);
