// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Prefer VITE_ inlined values at build time, fall back to runtime Lovable-provided
// globals when present (e.g. LOVABLE_SUPABASE_URL) to support deployments where
// OAuth integration isn't available.
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL ?? ((globalThis as any).LOVABLE_SUPABASE_URL ?? ""));
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? ((globalThis as any).LOVABLE_SUPABASE_PUBLISHABLE_KEY ?? ""));

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});